## Put comments here that give an overall description of what your
## functions do

## Creates a special matrix that is able to cache the result of
## 'solve' function. The new matrix type has the following functions
## 1. 'set' sets the value of the matrix
## 2. 'get' gets the value of the matrix
## 3. 'setinv' sets the value of the inverse matrix
## 4. 'getinv' gets the value of the inverse matrix
## Param: default a new matix
## Returns: a cacheMatrix object

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  
  set <- function (y) {
    x <<- y
    inv <<- NULL
  }
  
  get <- function() x
  
  setinv <- function(i) inv <<- i
  
  getinv <- function() inv
  
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## Solves a matrix. The function either computes the solve function
## for the passed matrix if this is the first time to compute for
## it, or if it isn't the first time it recall a pre-cahced value
## Param x: input matrix of type cacheMatrix (generated by makeCacheMatrix)
## Returns: inverse of matrix

cacheSolve <- function(x, ...) {
  cinv <- x$getinv()
  if (!is.null(cinv)) {
    message("getting cached data")
    return(cinv)
  }
  data <- x$get()
  cinv <- solve(data, ...)
  x$setinv(cinv)
  cinv
}
